# Generated by Django 4.1 on 2022-08-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibosonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divone',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibosonapp.options'),
        ),
        migrations.AlterField(
            model_name='divtwo',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibosonapp.options'),
        ),
    ]
