# Generated by Django 4.1 on 2022-08-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibosonapp', '0003_alter_divone_option_alter_divtwo_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='divtwo',
            name='id',
        ),
        migrations.AlterField(
            model_name='divone',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ibosonapp.options'),
        ),
        migrations.AlterField(
            model_name='divtwo',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ibosonapp.options'),
        ),
    ]
